class PrintMessage:
    def __init__(self):
        self.enter_option = "Enter option: "
        self.invalid_msg = "\033[31m Choose valid option \033[0m"
        self.err_msg = "\033[31m Resolving issue..Try again after some time\033[0m\n"
        self.email_address = "Enter email address: "
        self.enter_password = "Enter password: "
        self.invalid_info = "\033[31m Invalid Credentials \033[0m"
        self.food_added = "\033[32m \nFood item added to Menu \033[0m"
        self.noid_msg = "\033[31m Order id not found \033[0m"
        self.cancelled_msg = "\nOrder Cancelled"
        self.no_order_msg = "Cannot place order \033[31m :( \033[0m"
        self.choose_validtable = "Choose Available Seats/Table"
        self.book_confirm_msg = "\033[32m \nBooking confirmed \033[0m"
        self.invalidserving_msg = "\nInvalid serving size" 
        self.noitem_msg = "\033[31m\nFood Item Not available...Search anything else \033[0m"
        self.foodalready_present = "\nFood item already present in specific category"
        self.invalidamount_msg = "\nPaying Amount should be Greater than bill amount"
        self.notable_msg = "\033[31m New Table not added \033[0m"
        self.tableno = "Table No."
        self.availableseat = "Available Seats"  
        self.billpaid = " \033[32m \nBill paid :) \033[0m"
        self.amountreturned = "Amount returned"
        self.card_declined = "\033[31m \nCard Declined \033[0m"
        self.subtotal = "Subtotal"
        self.gst = "GST"
        self.totalbill = "Total Bill"
        self.namenot_aplha = "\nName should be in Alphabets"
        self.invalid_contact = "\nContact should be valid 10 digits" 
        self.invalid_email = "\nEnter valid Email....Ex: taif@mail.com"
        self.password_demo = "\nPassword must be atleast 8 characters long and include @ also"

print_obj = PrintMessage()
