class PrintMessage:
    def __init__(self):
        self.enter_option = "Enter option: "
        self.invalid_msg = "Choose valid option "
        self.err_msg = "Resolving issue..Try again after some time"
        self.email_address = "Enter email address: "
        self.enter_password = "Enter password: "
        self.invalid_info = "Invalid Credentials"
        self.food_added = "\nFood item added to Menu"
        self.noid_msg = "\nOrder id not found"
        self.cancelled_msg = "\nOrder Cancelled"
        self.no_order_msg = "Cannot place order :("
        self.choose_validtable = "Choose Available Seats/Table"
        self.book_confirm_msg = "\nBooking confirmed"
        self.invalidserving_msg = "\nInvalid serving size" 
        self.noitem_msg = "\nFood Item Not available...Search anything else"
        self.foodalready_present = "\nFood item already present in specific category"
        self.invalidamount_msg = "\nPaying Amount should be Greater than bill amount"
        self.notable_msg = "New Table not added"
        self.tableno = "Table No."
        self.availableseat = "Available Seats"  
        self.billpaid = "\nBill paid :)"
        self.amountreturned = "Amount returned"
        self.card_declined = "\nCard Declined"
        self.subtotal = "Subtotal"
        self.gst = "GST"
        self.totalbill = "Total Bill"
        self.namenot_aplha = "\nName should be in Alphabets"
        self.invalid_contact = "\nContact should be valid 10 digits" 
        self.invalid_email = "\nEnter valid Email....Ex: taif@mail.com"
        self.password_demo = "\nPassword must be atleast 8 characters long and include @ also"

print_obj = PrintMessage()
